### ISSUE TITLE
suggest to add Zenodo pub to GloBI Zenodo Community

### ISSUE THREAD

**Issue by jhpoelen** [SimoneLioy/Vespa-velutina-interactions#1]
Hey @SimoneLioy - your interaction datasets looks great!

If you'd like to point GloBI to your Zenodo pub instead of the latest and greatest Github version, suggest to add your Zenodo pub to the Global Biotic Interactions Zenodo community.

See e.g., https://globalbioticinteractions.org/contribute .

**Comment by SimoneLioy** [comment]
Hi @jhpoelen - many thanks for the help in uploading the data on GLOBI and this suggestion. 
I've edited the Zenodo pub for its inclusion in the Global Biotic Interactions Zenodo community.

**Comment by jhpoelen** [comment]
@SimoneLioy Thanks for being patient in going through this digital paperwork to get your datasets indexed by GloBI. 

Please allow some time to let GloBI update their search indexes to include your most recent results.

Also, if your have any additional questions / comments, please holler.
